[package]
name = "tun2proxy"
version = "0.8.3"
edition = "2024"
license = "MIT"
repository = "https://github.com/tun2proxy/tun2proxy"
homepage = "https://github.com/tun2proxy/tun2proxy"
authors = ["B. Blechschmidt", "ssrlive"]
description = "Tunnel interface to proxy"
readme = "README.md"
rust-version = "1.85"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[[bin]]
name = "tun2proxy-bin"
path = "src/bin/main.rs"

[[bin]]
name = "udpgw-server"
path = "src/bin/udpgw_server.rs"
required-features = ["udpgw"]

[features]
default = ["udpgw", "unshare"]
udpgw = []
unshare = ["tokio/process", "bincode-next"]

[dependencies]
async-trait = "0.1.92"
base64easy = "0.1.7"
chrono = { version = "0.4.45", default-features = false, features = [
    "clock",
    "std",
] }
clap = { version = "4.6.7", default-features = false, features = [
    "std",
    "help",
    "usage",
    "error-context",
    "derive",
    "suggestions",
] }
ctrlc2 = { version = "4.0.0", default-features = false, features = [
    "async",
    "termination",
] }
digest_auth = "0.3.1"
dotenvy = "0.15.7"
env_logger = { version = "0.11.11", default-features = false, features = [
    "humantime",
] }
hashlink = "0.12.2"
hickory-proto = "0.26.3"
httparse = "1.10.1"
ipstack = { version = "1.0.1" }
log = { version = "0.4.34", default-features = false, features = ["std"] }
percent-encoding = "2.3.2"
serde = { version = "1.0.229", features = ["derive"] }
shlex = "2.0.1"
socks5-impl = { version = "0.9.6", default-features = false, features = [
    "tokio",
    "serde",
] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "io-util",
    "sync",
] }
tokio-util = "0.7.19"
tproxy-config = { version = "^7.0.7", default-features = false }
tun = { version = "0.8.14", features = ["async"] }
udp-stream = { version = "0.0.12", default-features = false }
unicase = "2.9.0"
url = "2.5.8"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.15.1"
jni = { version = "0.22.4", default-features = false }

[target.'cfg(target_os="linux")'.dependencies]
bincode-next = { version = "3.1.1", optional = true }
tokio = { version = "1.53.1", default-features = false, optional = true, features = [
    "process",
] }

[target.'cfg(target_os="windows")'.dependencies]
windows-service = "0.8.1"

[target.'cfg(unix)'.dependencies]
daemonize = "0.5.0"
nix = { version = "0.31.3", default-features = false, features = [
    "fs",
    "socket",
    "uio",
] }

[build-dependencies]
chrono = { version = "0.4.45", default-features = false, features = [
    "clock",
    "std",
] }
serde_json = "1.0.151"

# [profile.release]
# strip = "symbols"
